# Generated by Django 2.2.1 on 2019-06-01 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('familiar', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='userstages',
            name='stageid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Stages'),
            preserve_default=False,
        ),
    ]
