# Generated by Django 2.2.1 on 2019-06-01 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190601_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstages',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Users'),
            preserve_default=False,
        ),
    ]
