# Generated by Django 2.2.1 on 2019-06-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userstages_userid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stages',
            new_name='Stage',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='UserStages',
            new_name='UserStage',
        ),
    ]
